Chinese Updates
hai-vr/vrw-t pull request #5
Opened 2023-08-13 15:57 UTC by XoF-eLtTiL

# Update the following files and synchronize them to the latest version

- 3201.Json Traditional Chinese
- 3202.json Simplified Chinese

2023-08-13 16:21 UTC, hai-vr requested changes

2023-08-13 16:21 UTC, hai-vr commented on 3202.json
> +  "SysVersionAnyoneIsHigher": "有人加入的 VRWare 版本比你的新。请快创建一个<color=orange>新的</color>
This is not a valid JSON file

2023-08-14 00:34 UTC, hai-vr commented
Leave a comment when you're satisfied with your changes and I'll do a squash & merge commit when I'm available, assuming that the files are clear

2023-08-14 04:40 UTC, XoF-eLtTiL commented
I don't have any more problems here. Could you please merge them when you have time?

2023-08-14 05:40 UTC, hai-vr approved these changes

2023-08-14 05:43 UTC, merged